# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4871aa4574b2d0bb26fe86fb91cca84e2fea3647b41a8fbb859037c41298ce75ba4fdc384204d5adf6790b8f8146a241bd08773284e4acf87841d9407223b182

test:
  secret_key_base: f5b725c70f5dbd6c96dede122d3bfb9b0fb0d6bb8ab5b20e5f878f3f756d784220e27b36e3cc264d274d78beb8bc3ef43d99f079c35526f43b38ccadaa7edd96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
